# Server port 설정
server:
  port: 8080

# datasource 명시
datasource:
  url: jdbc:h2:mem:testDb
  username: sa
  password:
  # h2 database driver
  driver-class-name: org.h2.Driver

## JPA 설정
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug